# Data Understanding

## Dataset: Melbourne House Prices Analysis


| Column | Description |
|---|---|
| `Suburb` | Name of the suburb where the property is located |
| `Address` | Street address of the property |
| `Rooms` | Number of rooms |
| `Type` | Property type: h (house, cottage, villa, terrace), u (unit, duplex), t (townhouse) |
| `Price` | Sale price in Australian dollars (AUD) |
| `Method` | Sale method: S (sold), SP (sold prior), PI (passed in), PN (sold prior, not disclosed), SN (sold, not disclosed), VB (vendor bid), W (withdrawn prior to auction), SA (sold after auction), SS (sold after auction, price not disclosed) |
| `SellerG` | Real estate agent or agency that sold the property |
| `Date` | Date the property was sold (text, format dd/mm/yyyy) |
| `Distance` | Distance from the Melbourne CBD (central business district) in km |
| `Postcode` | Postal code of the property |
| `CouncilArea` | Governing council for the area |
| `Regionname` | General region (West, North West, North, North East, and so on) |
| `Propertycount` | Number of properties in the suburb |

# Data Exploration and cleaning

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

### 1) Load Dataset

In [2]:
df = pd.read_csv('MELBOURNE_HOUSE_PRICES_LESS.csv')
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1220000.0,S,Marshall,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,1/04/2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,1/04/2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,1/04/2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31/03/2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31/03/2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31/03/2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

### 2)  Check Data Types

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 63023 entries, 0 to 63022
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         63023 non-null  str
 1   Address        63023 non-null  str
 2   Rooms          63023 non-null  int64
 3   Type           63023 non-null  str
 4   Price          48433 non-null  float64
 5   Method         63023 non-null  str
 6   SellerG        63023 non-null  str
 7   Date           63023 non-null  str
 8   Postcode       63023 non-null  int64
 9   Regionname     63023 non-null  str
 10  Propertycount  63023 non-null  int64
 11  Distance       63023 non-null  float64
 12  CouncilArea    63023 non-null  str
dtypes: float64(2), int64(3), str(8)
memory usage: 11.3 MB

##### Change data types

In [4]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
df['Postcode'] = df['Postcode'].astype(str)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 63023 entries, 0 to 63022
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         63023 non-null  str
 1   Address        63023 non-null  str
 2   Rooms          63023 non-null  int64
 3   Type           63023 non-null  str
 4   Price          48433 non-null  float64
 5   Method         63023 non-null  str
 6   SellerG        63023 non-null  str
 7   Date           63023 non-null  datetime64[us]
 8   Postcode       63023 non-null  str
 9   Regionname     63023 non-null  str
 10  Propertycount  63023 non-null  int64
 11  Distance       63023 non-null  float64
 12  CouncilArea    63023 non-null  str
dtypes: datetime64[us](1), float64(2), int64(2), str(8)
memory usage: 11.0 MB

### 3)  Check Duplicates

In [6]:
df.duplicated().sum()

np.int64(2)

##### Drop Duplicates

In [7]:
df = df.drop_duplicates().reset_index(drop=True)

### 4)  Check Summary statistics for Numerical columns

In [8]:
df.describe().round(2)

,Rooms,Price,Date,Propertycount,Distance
count,63021.00,48432.00,63021,63021.00,63021.00
mean,3.11,997897.99,2017-08-04 12:30:50.126148,7617.79,12.68
min,1.00,85000.00,2016-01-28 00:00:00,39.00,0.00
25%,3.00,620000.00,2016-12-03 00:00:00,4380.00,7.00
50%,3.00,830000.00,2017-09-03 00:00:00,6795.00,11.40
75%,4.00,1220000.00,2018-03-10 00:00:00,10412.00,16.70
max,31.00,11200000.00,2018-10-13 00:00:00,21650.00,64.10
std,0.96,593505.04,NaN,4424.48,7.59

### 5)  Check Summary statistics for Categorical columns

In [9]:
df.describe(include= ['str'])

,Suburb,Address,Type,Method,SellerG,Postcode,Regionname,CouncilArea
count,63021,63021,63021,63021,63021,63021,63021,63021
unique,380,57754,3,9,476,225,8,34
top,Reservoir,14 Moray St,h,S,Barry,3073,Southern Metropolitan,Boroondara City Council
freq,1241,7,45052,34063,6894,1241,17559,5132

### 6)  Check Missing Values

In [10]:
df.isna().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price            14589
Method               0
SellerG              0
Date                 0
Postcode             0
Regionname           0
Propertycount        0
Distance             0
CouncilArea          0
dtype: int64

In [11]:
df.isna().mean() * 100

Suburb            0.000000
Address           0.000000
Rooms             0.000000
Type              0.000000
Price            23.149426
Method            0.000000
SellerG           0.000000
Date              0.000000
Postcode          0.000000
Regionname        0.000000
Propertycount     0.000000
Distance          0.000000
CouncilArea       0.000000
dtype: float64

### 7)  Handling Missing Values

In [12]:
num_cols = df.select_dtypes(include= 'number').columns
num_cols

Index(['Rooms', 'Price', 'Propertycount', 'Distance'], dtype='str')

In [13]:
df[num_cols]

       Rooms      Price  Propertycount  Distance
0          3  1490000.0           4019       3.0
1          3  1220000.0           4019       3.0
2          3  1420000.0           4019       3.0
3          3  1515000.0           1543       7.5
4          2   670000.0           3464      10.4
...      ...        ...            ...       ...
63016      3   566000.0           5833      20.6
63017      3   500000.0           5833      20.6
63018      3   545000.0           5833      20.6
63019      3        NaN           7955      15.3
63020      4        NaN           1999      17.6

[63021 rows x 4 columns]

In [14]:
from sklearn.impute import KNNImputer

knn = KNNImputer(n_neighbors= 5)

df[num_cols] = knn.fit_transform(df[num_cols])

In [15]:
df.isna().mean() * 100

Suburb           0.0
Address          0.0
Rooms            0.0
Type             0.0
Price            0.0
Method           0.0
SellerG          0.0
Date             0.0
Postcode         0.0
Regionname       0.0
Propertycount    0.0
Distance         0.0
CouncilArea      0.0
dtype: float64

In [16]:
df[num_cols].describe().round(2)

          Rooms        Price  Propertycount  Distance
count  63021.00     63021.00       63021.00  63021.00
mean       3.11   1032888.12        7617.79     12.68
std        0.96    612897.45        4424.48      7.59
min        1.00     85000.00          39.00      0.00
25%        3.00    632300.00        4380.00      7.00
50%        3.00    857000.00        6795.00     11.40
75%        4.00   1252000.00       10412.00     16.70
max       31.00  11200000.00       21650.00     64.10

### 8)  Check outliers

#### 8.1 Detect Outliers with datasist

In [17]:
from datasist.structdata import detect_outliers

outlier_indices = detect_outliers(data= df, n= 0, features= num_cols)
outlier_indices

[8,
 21,
 129,
 137,
 150,
 163,
 209,
 219,
 249,
 259,
 277,
 348,
 349,
 381,
 384,
 398,
 401,
 421,
 454,
 455,
 457,
 461,
 478,
 492,
 494,
 506,
 524,
 561,
 565,
 574,
 576,
 620,
 645,
 669,
 696,
 701,
 707,
 719,
 744,
 747,
 789,
 790,
 803,
 811,
 813,
 828,
 854,
 868,
 906,
 918,
 926,
 962,
 994,
 998,
 1017,
 1026,
 1034,
 1038,
 1071,
 1082,
 1084,
 1121,
 1208,
 1225,
 1244,
 1294,
 1295,
 1296,
 1319,
 1326,
 1361,
 1400,
 1419,
 1424,
 1471,
 1496,
 1500,
 1520,
 1523,
 1544,
 1553,
 1554,
 1589,
 1623,
 1625,
 1629,
 1638,
 1660,
 1709,
 1725,
 1726,
 1764,
 1817,
 1818,
 1827,
 1828,
 1845,
 1861,
 1904,
 1906,
 1908,
 1959,
 1977,
 1986,
 2008,
 2016,
 2019,
 2055,
 2107,
 2155,
 2173,
 2207,
 2208,
 2231,
 2293,
 2323,
 2324,
 2340,
 2391,
 2392,
 2393,
 2496,
 2534,
 2547,
 2550,
 2584,
 2633,
 2638,
 2662,
 2688,
 2699,
 2705,
 2709,
 2710,
 2744,
 2758,
 2769,
 2809,
 2828,
 2836,
 2846,
 2859,
 2870,
 2891,
 2919,
 2928,
 2953,
 2982,
 2985,
 2988,
 3075,
 3081,
 3084,
 3093,
 3100,
 3148,
 3150,
 3168,
 3190,
 3252,
 3270,
 3284,
 3327,
 3334,
 3347,
 3375,
 3377,
 3388,
 3472,
 3547,
 3548,
 3594,
 3618,
 3646,
 3663,
 3670,
 3687,
 3690,
 3692,
 3694,
 3712,
 3720,
 3730,
 3732,
 3765,
 3807,
 3812,
 3825,
 3860,
 4034,
 4069,
 4077,
 4100,
 4139,
 4194,
 4195,
 4201,
 4215,
 4244,
 4281,
 4310,
 4338,
 4341,
 4352,
 4356,
 4404,
 4527,
 4614,
 4710,
 4744,
 4891,
 4953,
 4988,
 4998,
 5023,
 5026,
 5053,
 5074,
 5123,
 5124,
 5178,
 5200,
 5259,
 5265,
 5267,
 5268,
 5269,
 5314,
 5369,
 5371,
 5373,
 5374,
 5386,
 5409,
 5469,
 5470,
 5478,
 5523,
 5532,
 5536,
 5558,
 5577,
 5585,
 5606,
 5639,
 5649,
 5653,
 5654,
 5679,
 5712,
 5714,
 5720,
 5740,
 5742,
 5778,
 5822,
 5840,
 5842,
 5851,
 5860,
 5908,
 5933,
 6022,
 6044,
 6079,
 6081,
 6084,
 6086,
 6131,
 6144,
 6145,
 6177,
 6217,
 6219,
 6221,
 6223,
 6244,
 6293,
 6296,
 6410,
 6414,
 6431,
 6494,
 6521,
 6524,
 6548,
 6549,
 6562,
 6566,
 6590,
 6599,
 6602,
 6604,
 6624,
 6671,
 6744,
 6768,
 6777,
 6795,
 6808,
 6828,
 6831,
 6872,
 6873,
 6875,
 6978,
 7090,
 7096,
 7110,
 7151,
 7175,
 7221,
 7223,
 7230,
 7234,
 7237,
 7249,
 7273,
 7281,
 7287,
 7317,
 7318,
 7383,
 7389,
 7401,
 7413,
 7429,
 7450,
 7452,
 7479,
 7497,
 7498,
 7511,
 7517,
 7542,
 7577,
 7584,
 7588,
 7590,
 7596,
 7602,
 7615,
 7618,
 7637,
 7646,
 7649,
 7653,
 7655,
 7698,
 7705,
 7755,
 7764,
 7771,
 7825,
 7864,
 7874,
 7915,
 7938,
 7939,
 7952,
 7980,
 7982,
 8047,
 8098,
 8104,
 8124,
 8153,
 8158,
 8170,
 8199,
 8204,
 8209,
 8211,
 8221,
 8226,
 8230,
 8259,
 8280,
 8289,
 8302,
 8364,
 8398,
 8401,
 8412,
 8471,
 8521,
 8557,
 8602,
 8648,
 8651,
 8687,
 8694,
 8719,
 8723,
 8728,
 8755,
 8773,
 8788,
 8813,
 8824,
 8866,
 8875,
 8888,
 8941,
 8999,
 9024,
 9045,
 9074,
 9080,
 9082,
 9089,
 9118,
 9204,
 9280,
 9300,
 9324,
 9338,
 9369,
 9373,
 9411,
 9421,
 9464,
 9465,
 9469,
 9478,
 9497,
 9498,
 9502,
 9556,
 9573,
 9585,
 9720,
 9731,
 9740,
 9766,
 9806,
 9818,
 9860,
 9881,
 9905,
 9968,
 9970,
 10008,
 10015,
 10017,
 10019,
 10146,
 10151,
 10174,
 10222,
 10223,
 10268,
 10272,
 10283,
 10422,
 10427,
 10477,
 10479,
 10482,
 10483,
 10505,
 10509,
 10522,
 10548,
 10562,
 10591,
 10595,
 10604,
 10612,
 10627,
 10660,
 10730,
 10825,
 10828,
 10829,
 10846,
 10849,
 10851,
 10887,
 10901,
 10910,
 10911,
 10932,
 10933,
 10934,
 10945,
 10967,
 10968,
 11013,
 11049,
 11058,
 11137,
 11171,
 11194,
 11237,
 11260,
 11313,
 11315,
 11324,
 11330,
 11401,
 11453,
 11505,
 11520,
 11532,
 11553,
 11554,
 11568,
 11571,
 11572,
 11575,
 11576,
 11606,
 11607,
 11620,
 11633,
 11642,
 11644,
 11654,
 11656,
 11665,
 11710,
 11711,
 11731,
 11758,
 11772,
 11811,
 11830,
 11838,
 11882,
 11939,
 12053,
 12054,
 12056,
 12087,
 12088,
 12089,
 12170,
 12173,
 12179,
 12191,
 12201,
 12202,
 12255,
 12324,
 12330,
 12345,
 12388,
 12403,
 12438,
 12447,
 12464,
 12466,
 12471,
 12472,
 12500,
 12506,
 12565,
 12566,
 12576,
 12661,
 12727,
 12802,
 12845,
 12906,
 12909,
 12948,
 12966,
 12995,
 12996,
 13013,
 13017,
 13021,
 13022,
 13025,
 13030,
 13056,
 13070,
 13075,
 13099,
 13111,
 13130,
 13147,
 13215,
 13265,
 13301,
 13346,
 13392,
 13395,
 13431,
 13438,
 13463,
 13467,
 13472,
 13499,
 13517,
 13532,
 13557,
 13568,
 13610,
 13619,
 13632,
 13685,
 13743,
 13768,
 13789,
 13818,
 13824,
 13826,
 13833,
 13862,
 13955,
 14004,
 14053,
 14054,
 14063,
 14066,
 14086,
 14101,
 14104,
 14112,
 14131,
 14141,
 14150,
 14187,
 14195,
 14214,
 14215,
 14216,
 14230,
 14246,
 14272,
 14287,
 14289,
 14308,
 14335,
 14338,
 14339,
 14340,
 14341,
 14347,
 14393,
 14394,
 14421,
 14431,
 14499,
 14517,
 14566,
 14589,
 14592,
 14600,
 14625,
 14634,
 14645,
 14660,
 14661,
 14663,
 14708,
 14736,
 14776,
 14786,
 14820,
 14830,
 14833,
 14850,
 14851,
 14887,
 14888,
 14893,
 14894,
 14900,
 14907,
 14914,
 14915,
 14941,
 14945,
 14973,
 14974,
 14977,
 14990,
 15021,
 15060,
 15080,
 15084,
 15120,
 15128,
 15129,
 15130,
 15157,
 15160,
 15185,
 15186,
 15282,
 15286,
 15318,
 15320,
 15326,
 15381,
 15388,
 15407,
 15414,
 15417,
 15421,
 15426,
 15477,
 15548,
 15602,
 15606,
 15642,
 15644,
 15645,
 15680,
 15687,
 15694,
 15717,
 15733,
 15751,
 15768,
 15810,
 15892,
 15935,
 15951,
 15963,
 15973,
 15983,
 15998,
 16032,
 16042,
 16067,
 16143,
 16144,
 16154,
 16235,
 16249,
 16250,
 16252,
 16281,
 16314,
 16316,
 16331,
 16351,
 16366,
 16444,
 16451,
 16495,
 16503,
 16519,
 16556,
 16631,
 16634,
 16642,
 16672,
 16674,
 16690,
 16694,
 16831,
 16881,
 16954,
 16971,
 16982,
 17013,
 17014,
 17047,
 17048,
 17052,
 17056,
 17090,
 17097,
 17100,
 17109,
 17116,
 17141,
 17166,
 17212,
 17248,
 17253,
 17275,
 17281,
 17298,
 17364,
 17439,
 17457,
 17481,
 17516,
 17517,
 17521,
 17526,
 17530,
 17554,
 17584,
 17589,
 17631,
 17643,
 17739,
 17746,
 17769,
 17823,
 17847,
 17859,
 17860,
 17863,
 17867,
 17870,
 17871,
 17914,
 17916,
 17932,
 17933,
 17934,
 17935,
 17938,
 17994,
 17999,
 18062,
 18081,
 18091,
 18113,
 18114,
 18121,
 18125,
 18139,
 18141,
 18145,
 18183,
 18214,
 18216,
 18217,
 18242,
 18250,
 18295,
 18329,
 18348,
 18353,
 18354,
 18357,
 18467,
 18546,
 18556,
 18559,
 18587,
 18590,
 18603,
 18652,
 18707,
 18711,
 18789,
 18813,
 18853,
 18854,
 18927,
 18934,
 18935,
 18987,
 19000,
 19017,
 19046,
 19052,
 19053,
 19069,
 19083,
 19111,
 19120,
 19131,
 19138,
 19147,
 19164,
 19229,
 19256,
 19273,
 19321,
 19329,
 19346,
 19366,
 19404,
 19433,
 19465,
 19520,
 19574,
 19578,
 19579,
 19582,
 19629,
 19651,
 19653,
 19677,
 19695,
 19701,
 19754,
 19807,
 19813,
 19837,
 19854,
 19862,
 19932,
 19943,
 19944,
 19945,
 19962,
 19964,
 19993,
 20009,
 20057,
 20059,
 20120,
 20255,
 20256,
 20282,
 20302,
 20303,
 20304,
 20305,
 20311,
 20313,
 20336,
 20337,
 20341,
 20346,
 20373,
 20374,
 20380,
 20413,
 20504,
 20515,
 20517,
 20573,
 20583,
 20634,
 20646,
 20701,
 20711,
 20769,
 20810,
 20840,
 20850,
 20914,
 20929,
 20963,
 20965,
 21033,
 21040,
 21058,
 21081,
 21151,
 21171,
 21173,
 21191,
 21192,
 21195,
 21227,
 21243,
 21246,
 21247,
 21282,
 21302,
 21304,
 21330,
 21336,
 21423,
 21448,
 21469,
 21474,
 21504,
 21511,
 21530,
 21540,
 21568,
 21604,
 21620,
 21621,
 21632,
 21729,
 21730,
 21741,
 21773,
 21774,
 21776,
 21782,
 21796,
 21817,
 21838,
 21865,
 21884,
 21908,
 21918,
 21925,
 21941,
 21965,
 21966,
 21993,
 22021,
 22065,
 22111,
 22155,
 22156,
 22166,
 22167,
 22168,
 22180,
 22231,
 22238,
 ...]

In [18]:
len(outlier_indices)

8907

In [19]:
len(outlier_indices)/len(df)*100

14.133384110058552

In [20]:
for col in num_cols:
    outliers_count=len(detect_outliers(data= df, n= 0, features= [col]))
    percentage=outliers_count/len(df)*100
    print(col,":", outliers_count,"--->",round(percentage,2),"%")

Rooms : 2644 ---> 4.2 %
Price : 3222 ---> 5.11 %
Propertycount : 1241 ---> 1.97 %
Distance : 1996 ---> 3.17 %

#### 8.2 Detect Outliers with visualization

####  Rooms outlier

In [21]:
px.box(data_frame= df, x= 'Rooms')

In [22]:
df[df['Rooms'] > 10][['Suburb', 'Type', 'Rooms', 'Price', 'Distance']]

               Suburb Type  Rooms      Price  Distance
7452    Fitzroy North    h   11.0  3880000.0       3.6
7952          Clayton    h   12.0  2056000.0      16.7
21336          Melton    h   12.0   710000.0      31.7
39845        Hawthorn    h   12.0  4700000.0       5.3
55465  Wantirna South    h   31.0   990000.0      14.7
58868         Preston    h   12.0  1438000.0       8.4
59739         Mitcham    h   16.0  5000000.0      17.2

####  Handling Rooms outlier

In [23]:
df = df.drop(55465).reset_index(drop=True)

In [24]:
px.box(data_frame= df, x= 'Rooms')

# Save Cleaned Dataframe

In [25]:
df.to_parquet('cleaned_data.parquet')

In [26]:
df.to_csv('cleaned_data.csv')

In [27]:
cleaned_df = pd.read_parquet('cleaned_data.parquet')

# Data Analysis

###   What is the average property prices for every region ?

In [28]:
successful_sales = cleaned_df[cleaned_df["Method"].isin(["S", "SP", "SA"])]
avg_by_region = (successful_sales.groupby('Regionname')['Price']
                   .mean()
                   .sort_values(ascending=False)
                   .reset_index())

avg_by_region.index = avg_by_region.index + 1
avg_by_region

                   Regionname         Price
1       Southern Metropolitan  1.428597e+06
2        Eastern Metropolitan  1.063882e+06
3  South-Eastern Metropolitan  8.379604e+05
4       Northern Metropolitan  8.348922e+05
5        Western Metropolitan  7.988132e+05
6            Eastern Victoria  6.874515e+05
7           Northern Victoria  6.284191e+05
8            Western Victoria  4.105515e+05

In [29]:
px.bar(data_frame=avg_by_region, x='Price', y='Regionname',
       color='Regionname', text_auto='.2s',
       title='Average Property Prices by Region',labels={'Regionname': 'Region Name'})

###   What are the top 10 most expensive suburbs by average price?

In [30]:
top10_expensive = (successful_sales.groupby('Suburb')['Price']
                   .mean()
                   .sort_values(ascending=False)
                   .head(10)
                   .reset_index())

top10_expensive .index = top10_expensive .index + 1
top10_expensive

          Suburb         Price
1       Deepdene  2.427974e+06
2     Canterbury  2.355349e+06
3    Middle Park  2.318219e+06
4       Brighton  2.089257e+06
5        Malvern  2.087497e+06
6    Albert Park  1.967831e+06
7        Kooyong  1.873659e+06
8   Ivanhoe East  1.837346e+06
9            Kew  1.817422e+06
10        Balwyn  1.812690e+06

In [31]:
px.bar(data_frame=top10_expensive , x='Suburb', y='Price',
       color='Suburb', text_auto='.2s',
       title='Top 10 most expensive suburbs by average price')

###  What are the 10 cheapest suburbs by average price?

In [32]:
top10_cheapest = (successful_sales.groupby('Suburb')['Price']
                    .mean()
                    .sort_values()
                    .head(10)
                    .reset_index())

top10_cheapest.index = top10_cheapest.index + 1
top10_cheapest

             Suburb          Price
1            Darley  380000.000000
2         Kurunjang  381111.111111
3          Cockatoo  397000.000000
4      Melton South  398669.587629
5   Mount Dandenong  405000.000000
6            Melton  411000.000000
7       Melton West  420637.254902
8        Don Valley  441000.000000
9     Bacchus Marsh  449000.000000
10          Warneet  450000.000000

In [33]:
px.bar(data_frame=top10_cheapest, x='Suburb', y='Price',
       color='Suburb', text_auto='.2s',
       title='Top 10 Cheapest Suburbs by Average Price')

### Which property type is sold the most?

In [34]:
sold_properties = cleaned_df[~cleaned_df['Method'].isin(['PI', 'W','VB'])]
type_counts = sold_properties['Type'].value_counts().reset_index()
type_counts.columns = ['Type', 'Count']
type_counts.index = type_counts.index + 1
type_counts

  Type  Count
1    h  33858
2    u   8558
3    t   4374

In [35]:
px.pie(data_frame=type_counts, names='Type', values='Count',title='Percentage of sold property types ')

### What is the average price by property type?

In [36]:
avg_price_by_type = successful_sales.groupby('Type')['Price'].mean().reset_index()
avg_price_by_type.columns = ['Type', 'Average Price']
avg_price_by_type.index = avg_price_by_type.index + 1
avg_price_by_type

  Type  Average Price
1    h   1.121005e+06
2    t   9.317463e+05
3    u   6.614265e+05

In [37]:
px.bar(data_frame=avg_price_by_type, x='Type', y='Average Price',
       color='Type', text_auto='.2s',
       title='Average Price by Property Type')

### What is the most common sale method?

In [38]:
method_counts = cleaned_df['Method'].value_counts().reset_index()
method_counts.columns = ['Method', 'Count']
method_counts.index = method_counts.index + 1
method_counts

  Method  Count
1      S  34062
2     PI   9790
3     SP   8914
4     VB   5956
5     SN   2674
6     PN    651
7      W    484
8     SA    416
9     SS     73

In [39]:
method_counts = sold_properties['Method'].value_counts().reset_index()
method_counts.columns = ['Method', 'Count']
method_counts.index = method_counts.index + 1
method_counts

  Method  Count
1      S  34062
2     SP   8914
3     SN   2674
4     PN    651
5     SA    416
6     SS     73

In [40]:
px.bar(
    data_frame=method_counts,
    x='Method',
    y='Count',
    color='Method',
    text_auto=True,
    title='Most Common Successful Sale Methods')

### How many properties were unsold?

In [41]:
unsold_df = cleaned_df[cleaned_df['Method'].isin(['PI', 'W', 'VB'])]
unsold_counts = unsold_df['Method'].value_counts().reset_index()
unsold_counts.columns = ['Method', 'Count']
unsold_counts.index= unsold_counts.index + 1
unsold_counts

  Method  Count
1     PI   9790
2     VB   5956
3      W    484

In [42]:
px.bar(
    data_frame=unsold_counts,
    x='Method',
    y='Count',
    color='Method',
    text_auto=True,
    title='Unsold Properties')

### Which sellers (agents) sold the most properties?

In [43]:
top_sellers = sold_properties['SellerG'].value_counts().head(10).reset_index()
top_sellers.columns = ['Seller', 'Count']
top_sellers.index=top_sellers.index+1
top_sellers

           Seller  Count
1           Barry   5173
2          Jellis   3924
3          Nelson   3524
4             Ray   3500
5   hockingstuart   3253
6          Buxton   2392
7        Marshall   2039
8       Fletchers   1107
9          Biggin   1096
10      Harcourts    929

In [44]:
px.bar(
    data_frame=top_sellers,
    x='Count',
    y='Seller',
    color='Count',
    text_auto=True,
    title='Top 10 Real Estate Sellers')

### Which year has the highest number of sales?

In [45]:
sold_properties['Year'] = sold_properties['Date'].dt.year.astype(str)
sales_per_year = sold_properties['Year'].value_counts().reset_index()
sales_per_year.columns = ['Year', 'Sales Count']
sales_per_year.index=sales_per_year.index + 1
sales_per_year

   Year  Sales Count
1  2017        20101
2  2016        13378
3  2018        13311

In [46]:
px.bar(sales_per_year,
    x='Year',
    y='Sales Count',
    text='Sales Count',  
    color='Year',        
    title='Total Number of Sales per Year',)

### What is the Annual revenue?

In [47]:
successful_sales['Year'] = successful_sales['Date'].dt.year.astype(str)

Annual_revenue = (successful_sales.groupby('Year')['Price'].sum().reset_index())
Annual_revenue.columns = ['Year', 'Total Revenue']
Annual_revenue.index=Annual_revenue.index + 1 
Annual_revenue

   Year  Total Revenue
1  2016   1.238753e+10
2  2017   1.933799e+10
3  2018   1.242223e+10

In [48]:
px.bar(Annual_revenue,
    x='Year',
    y='Total Revenue',
    text='Total Revenue',  
    color='Year', 
    text_auto=True ,
    title='Annual Total Revenue')

In [49]:
px.line(data_frame=Annual_revenue, 
                    x='Year', 
                    y='Total Revenue', 
                    markers=True,
                    title='Annual Total Revenue')

### What is the monthly revenue?

In [50]:
successful_sales['YearMonth'] = successful_sales['Date'].dt.strftime('%Y-%m')
monthly_revenue = successful_sales.groupby('YearMonth')['Price'].sum().reset_index()
monthly_revenue.index=monthly_revenue.index + 1
monthly_revenue

   YearMonth         Price
1    2016-01  1.094510e+07
2    2016-02  6.448083e+07
3    2016-04  5.768713e+08
4    2016-05  1.710125e+09
5    2016-06  1.361893e+09
6    2016-07  7.789891e+08
7    2016-08  1.439548e+09
8    2016-09  1.746506e+09
9    2016-10  1.057927e+09
10   2016-11  2.277910e+09
11   2016-12  1.362338e+09
12   2017-02  9.526022e+08
13   2017-03  1.491502e+09
14   2017-04  1.976128e+09
15   2017-05  2.185047e+09
16   2017-06  1.452038e+09
17   2017-07  1.432584e+09
18   2017-08  1.410352e+09
19   2017-09  2.009858e+09
20   2017-10  2.384700e+09
21   2017-11  1.898690e+09
22   2017-12  2.144482e+09
23   2018-01  1.022270e+09
24   2018-02  1.317904e+09
25   2018-03  2.224301e+09
26   2018-04  1.317802e+09
27   2018-05  1.593361e+09
28   2018-06  1.397199e+09
29   2018-07  7.372051e+08
30   2018-08  9.990396e+08
31   2018-09  1.343121e+09
32   2018-10  4.700265e+08

In [51]:
px.line(data_frame=monthly_revenue, 
                    x='YearMonth', 
                    y='Price', 
                    markers=True,
                    labels={'YearMonth':'Month-Year' , 'Price':'Total Revenue'} ,
                    title='Monthly Total Revenue')

### What is the daily revenue?

In [52]:
Daily_revenue = ( successful_sales.groupby('Date')['Price'] .sum().reset_index())
Daily_revenue.index=Daily_revenue.index + 1
Daily_revenue

          Date        Price
1   2016-01-28   10945100.0
2   2016-02-04   64480827.6
3   2016-04-16  387045150.0
4   2016-04-23  189826118.0
5   2016-05-07  471498460.6
..         ...          ...
108 2018-09-08  357341337.0
109 2018-09-15  341688364.6
110 2018-09-22  371470618.0
111 2018-10-06  229256770.0
112 2018-10-13  240769752.0

[112 rows x 2 columns]

In [53]:
 px.line( data_frame=Daily_revenue,
    x='Date',
    y='Price',
    markers=True,
     labels={'Price':'Total Revenue'},
    title='Daily Total Revenue')

### Are properties closer to the city center more expensive?

In [54]:
price_by_distance = successful_sales.groupby(['Distance','Type'])['Price'].median().reset_index()
price_by_distance.index=price_by_distance.index+1
price_by_distance.head(10)

    Distance Type      Price
1        0.0    h  1630000.0
2        0.0    u   681500.0
3        0.7    h  1017500.0
4        0.7    u   600000.0
5        1.3    h  3345000.0
6        1.3    t  1350000.0
7        1.3    u   872000.0
8        1.4    t  1370000.0
9        1.4    u   430000.0
10       1.6    h  1257500.0

In [55]:
 px.scatter(data_frame=price_by_distance,
    x='Distance',  
    y='Price', 
    color='Type' ,    
    title='Property Price vs Distance from City Center')

### How are the numerical columns correlated?

In [56]:

correlation_matrix = successful_sales.corr(numeric_only=True).round(2)
correlation_matrix

               Rooms  Price  Propertycount  Distance
Rooms           1.00   0.42          -0.05      0.27
Price           0.42   1.00          -0.06     -0.29
Propertycount  -0.05  -0.06           1.00      0.01
Distance        0.27  -0.29           0.01      1.00

In [57]:

px.imshow(
    correlation_matrix,
    text_auto='.2f', 
    color_continuous_scale='RdBu_r', 
    title='Correlation Matrix of Numerical Features'
)

In [58]:
px.scatter(
    data_frame=successful_sales,
    x='Distance',
    y='Price',
    color='Type',title='Property Price vs Distance from CBD by Property Type',
    labels={
        'Distance': 'Distance from CBD (km)',
        'Price': 'Price (AU$)',
        'Type': 'Property Type'})